# 默认前缀
server:
  contextPath=/


spring:
  # 整合JSP
  mvc:
    view:
    # 页面默认前缀目录
      prefix: /WEB-INF/view/
    # 响应页面默认后缀
      suffix: .jsp
      view-names: '*'
    # 访问静态资源要加上 static
    static-path-pattern: /**
  # 整合thymeleaf
  thymeleaf:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    # 禁用缓存
    cache: false
    view-names: html/*,vue/*,jsps/*,templates/*,error/*
  # 设置字符集
#  http:
  #  encoding:
    #  charset: UTF-8
    #  force: false
    #  enabled: true
shiro:
  user:
    # 登录地址
    loginUrl: /login/index
    # 权限认证失败地址
    unauthorizedUrl: /login/unauth
    # 首页地址
    indexUrl: /index

connection:
  username: admin
  remoteAddress: 127.0.0.1